#!/bin/sh


sample_conf__DEFAULT__name1='this is a test' \
sample_conf__DEFAULT__name2=val2 \
delete__sample_conf__deprecated__name3=1 \
delete__sample_conf__junk=1 \
python iniconfigurator.py "$@" sample.conf > sample.conf.new

